[package]
name = "devenv-run-tests"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
devenv.workspace = true
tempfile.workspace = true
tokio.workspace = true
miette.workspace = true
