name: "Examples"

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout"
        required: false
        type: string

jobs:
  generate-examples:
    runs-on: [self-hosted, linux, X64]
    outputs:
      examples: ${{ steps.set-examples.outputs.examples }}
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - name: Fetch examples to run
        id: set-examples
        run: |
          set -euxo pipefail
          json=$(nix shell nixpkgs#tree -c tree -J -L 1 examples | nix shell nixpkgs#jq -c jq -c '[.[0].contents[] | .name]')
          echo "examples=$json" >> $GITHUB_OUTPUT

  examples:
    name: ${{ matrix.example }} (${{ join(matrix.systems.runs-on) }})
    needs: [generate-examples]
    strategy:
      fail-fast: false
      matrix:
        systems:
          - system: "aarch64-linux"
            runs-on: [self-hosted, linux, ARM64]
          - system: "x86_64-linux"
            runs-on: [self-hosted, linux, X64]
          - system: "aarch64-darwin"
            runs-on: [self-hosted, macOS, ARM64]
          - system: "x86_64-darwin"
            runs-on: [macos-13]
        example: ${{ fromJSON(needs.generate-examples.outputs.examples) }}
    runs-on: ${{ matrix.systems.runs-on }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build devenv
        run: |
          path=$(nix build -L --print-out-paths)
          echo "$path/bin" >> $GITHUB_PATH
      - name: Run examples
        run: devenv-run-tests --only ${{ matrix.example }} examples