name: "Build & Test"

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements.in"
      - "requirements.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    secrets: inherit

  examples:
    needs: test
    uses: ./.github/workflows/examples.yml
    secrets: inherit